// 原创数量关系模拟百题v2，非国考真题。
// a为0起始下标；新版UID不继承旧错题成绩。
// 发布资格由外部release_manifest.json绑定的独立审计hash决定，题目不自批发布状态。
window.HAND_LADDER_100 = [
  {
    "uid": "hand100:v2:001",
    "replacesUid": "hand100:001",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "总量差量",
    "t": "钩子",
    "s": "8名工作人员测评平均76分，加入1人后9人平均78分。新加入者得多少分？",
    "o": [
      "94",
      "80",
      "90",
      "96"
    ],
    "a": 0,
    "e": "把78分看作原8人每人补2分，新增者还要承担自己的78分，得78+8×2=94分。无需分别乘出两个总分。",
    "tr": "只算平均分差2分，会丢掉人数这个权重。",
    "signal": "人数变化而总分可加，先把平均数还原为总量。",
    "family": "平均数增员",
    "template": "平均数增员",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:002",
    "replacesUid": "hand100:002",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "比例",
    "t": "钩子",
    "s": "甲、乙两队共有96人，人数比为3∶5。从乙调6人到甲后，甲队有多少人？",
    "o": [
      "30",
      "42",
      "36",
      "48"
    ],
    "a": 1,
    "e": "共8份，每份12人，甲原有36人，再加6得42人。调动不改变两队总人数。",
    "tr": "不要先改变比例中的3和5；6是人数，不是份数。",
    "signal": "比例配合总人数，先设份，再执行调动。",
    "family": "定量转移",
    "template": "定量转移",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:003",
    "replacesUid": "hand100:003",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "总量差量",
    "t": "钩子",
    "s": "单位采购同一种文件夹，数量不变。单价提高2元后，采购总费用增加120元。共采购多少个？",
    "o": [
      "30",
      "62",
      "60",
      "120"
    ],
    "a": 2,
    "e": "每个多付2元，总共多付120元，数量=120÷2=60。原单价完全不用求。",
    "tr": "把120当作原总价，反而引入无关未知量。",
    "signal": "数量不变时，总费用差=单价差×数量。",
    "family": "单价变化的总差",
    "template": "单价变化的总差",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:004",
    "replacesUid": "hand100:004",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "整除",
    "t": "钩子",
    "s": "一次培训中，参加实操的人数恰好占总人数的37.5%。总人数大于75且小于85，问总人数是多少？",
    "o": [
      "78",
      "82",
      "84",
      "80"
    ],
    "a": 3,
    "e": "37.5%=3/8，人数为整数意味着总人数是8的倍数；给定开区间里只有80。",
    "tr": "百分比是精确值，不能允许四舍五入后的比例。",
    "signal": "精确百分数先约成最简分数，用分母筛人数。",
    "family": "精确比例与人数范围",
    "template": "精确比例与人数范围",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:005",
    "replacesUid": "hand100:005",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "工程",
    "t": "钩子",
    "s": "一项工程甲独做12天、乙独做18天完成，效率恒定且合作效率相加。两人合作3天后，剩余占总工程量的多少？",
    "o": [
      "7/12",
      "5/12",
      "1/2",
      "2/3"
    ],
    "a": 0,
    "e": "设总量36，甲乙每天分别完成3、2，3天完成15，剩21，即7/12。",
    "tr": "5/12是已完成比例，不是剩余比例。",
    "signal": "工期分母容易公倍数化时，用整数工作量。",
    "family": "合作后剩余",
    "template": "合作后剩余",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:006",
    "replacesUid": "hand100:006",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "工程",
    "t": "转化钩",
    "s": "完成同一任务，甲乙合作需12天，甲丙合作需15天，乙丙合作需20天。三人效率恒定可相加，三人一起做需多少天？",
    "o": [
      "5",
      "10",
      "8",
      "12"
    ],
    "a": 1,
    "e": "设总量60，三对效率为5、4、3；相加把每人算了两次，所以三人效率为6，需10天。",
    "tr": "三对效率之和必须除以2，不是直接当三人效率。",
    "signal": "每人出现在两对里，先识别重复计数。",
    "family": "成对效率反推总体",
    "template": "成对效率反推总体",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：三对效率要识别每人被重复计算两次，需要求和后再除2。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:007",
    "replacesUid": "hand100:007",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "行程",
    "t": "钩子",
    "s": "汽车沿同一路线往返，不停留，去程速度60千米/时，返程40千米/时。全程平均速度是多少千米/时？",
    "o": [
      "45",
      "50",
      "48",
      "52"
    ],
    "a": 2,
    "e": "设单程120千米，往返共240千米、用时2+3=5小时，平均48。只需一个方便的假设路程。",
    "tr": "50是速度的算术平均，不适用于等路程的快慢两段。",
    "signal": "平均速度始终是总路程除以总时间。",
    "family": "等路程平均速度",
    "template": "等路程平均速度",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:008",
    "replacesUid": "hand100:008",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "行程",
    "t": "钩子",
    "s": "周长400米的环形跑道上，两人从同一点同时反向匀速出发，速度为3米/秒、5米/秒。首次再次相遇需多少秒？",
    "o": [
      "40",
      "80",
      "200",
      "50"
    ],
    "a": 3,
    "e": "首次再相遇合走一圈，相对速度8米/秒，400÷8=50秒。",
    "tr": "反向用速度和，同向追及才用速度差。",
    "signal": "先确定合走一圈，而非各跑一圈。",
    "family": "反向相对路程",
    "template": "反向相对路程",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:009",
    "replacesUid": "hand100:009",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "极值",
    "t": "钩子",
    "s": "袋内有5个红球和4个蓝球，除颜色外完全相同。不看颜色逐个不放回取球，至少取几个才能保证取到红球？",
    "o": [
      "5",
      "2",
      "4",
      "6"
    ],
    "a": 0,
    "e": "最坏先取走全部4个蓝球，第5个必红。保证问题不需要算概率。",
    "tr": "红球较多并不意味着取1个就能保证。",
    "signal": "看到“保证”，先安排最不利顺序。",
    "family": "最不利抽取",
    "template": "最不利抽取",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:010",
    "replacesUid": "hand100:010",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "极值",
    "t": "转化钩",
    "s": "26名志愿者全部分组，每组至少1人，各组人数两两不同。最多能分多少组？",
    "o": [
      "5",
      "6",
      "7",
      "8"
    ],
    "a": 1,
    "e": "7组至少需1+…+7=28人，不可行；6组可取1、2、3、4、5、11，共26人。下界与可行构造缺一不可。",
    "tr": "只证明7组不行，还要证明6组确实能安排。",
    "signal": "组数最大，先让各组人数取最小互异正整数。",
    "family": "互异正整数最小和",
    "template": "互异正整数最小和",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：互异人数先用最小总和证明组数上界，再构造余量分配达到上界。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:011",
    "replacesUid": "hand100:011",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "组合",
    "t": "钩子",
    "s": "从6名不同工作人员中选2人参会，甲、乙不能同时入选。共有多少种选法？",
    "o": [
      "10",
      "15",
      "14",
      "28"
    ],
    "a": 2,
    "e": "全部C(6,2)=15种，只减掉甲乙这一对，得14。",
    "tr": "不能减去所有包含甲或乙的情况；只禁止同时出现。",
    "signal": "“不能同时”且坏情况很少，先做补集。",
    "family": "选人排除特定对子",
    "template": "选人排除特定对子",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:012",
    "replacesUid": "hand100:012",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "组合",
    "t": "钩子",
    "s": "5名不同人员排成一列，甲乙必须相邻，且二人前后顺序不限。共有多少种排法？",
    "o": [
      "24",
      "36",
      "60",
      "48"
    ],
    "a": 3,
    "e": "把甲乙捆成一块，和另3人共4个对象，排法4!×2=48。",
    "tr": "捆绑后还要乘甲乙内部的2种次序。",
    "signal": "必须相邻，把多个对象压成一个块。",
    "family": "相邻捆绑",
    "template": "相邻捆绑",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:013",
    "replacesUid": "hand100:013",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "概率",
    "t": "钩子",
    "s": "袋中3红球、2蓝球，球除颜色外相同，等可能地不放回抽2球。两球均为红色的概率是多少？",
    "o": [
      "3/10",
      "2/5",
      "9/25",
      "3/5"
    ],
    "a": 0,
    "e": "从5球选2共10种，从3红球选2共3种，概率3/10；也可算3/5×2/4。",
    "tr": "第二次红球比例改变，不能算(3/5)²。",
    "signal": "不放回会改变第二次的分子、分母。",
    "family": "不放回同色抽取",
    "template": "不放回同色抽取",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:014",
    "replacesUid": "hand100:014",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "概率",
    "t": "钩子",
    "s": "甲、乙各独立完成一次检测，检出同一故障的概率分别为3/5、1/2。至少一人检出的概率是多少？",
    "o": [
      "3/10",
      "4/5",
      "1/2",
      "9/10"
    ],
    "a": 1,
    "e": "反面是两人都未检出：概率(2/5)×(1/2)=1/5，所以所求4/5。",
    "tr": "直接相加会重复计入两人都检出的情况。",
    "signal": "至少一个成功，优先算全部失败。",
    "family": "独立事件补集",
    "template": "独立事件补集",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:015",
    "replacesUid": "hand100:015",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "几何",
    "t": "钩子",
    "s": "三角形ABC中，D、E分别是AB、AC的中点。三角形ADE面积为9平方米，ABC面积是多少平方米？",
    "o": [
      "18",
      "27",
      "36",
      "45"
    ],
    "a": 2,
    "e": "小三角形两边均为对应边的一半，面积为原来的1/4，所以大面积36。",
    "tr": "把边长比1/2直接用于面积，会误选18。",
    "signal": "两条方向的长度都缩放，面积要乘两次比例。",
    "family": "线性比到面积比",
    "template": "线性比到面积比",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:016",
    "replacesUid": "hand100:016",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "几何",
    "t": "钩子",
    "s": "用40米围栏围成一个长方形，不留缺口。其面积最大是多少平方米？",
    "o": [
      "80",
      "96",
      "120",
      "100"
    ],
    "a": 3,
    "e": "长宽之和为20，越接近乘积越大；取10×10，面积100。无需枚举所有长宽。",
    "tr": "固定的是周长40，长宽之和只有20。",
    "signal": "和固定时，乘积在两量相等处最大。",
    "family": "固定周长的乘积上界",
    "template": "固定周长的乘积上界",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:017",
    "replacesUid": "hand100:017",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "周期",
    "t": "钩子",
    "s": "某月有31天，1日是星期五。该月共有多少个星期日？",
    "o": [
      "5",
      "3",
      "4",
      "6"
    ],
    "a": 0,
    "e": "31=4×7+3，额外3天是星期五、六、日，因此星期日有5个。",
    "tr": "不能把31÷7向下取整后就忽略余日。",
    "signal": "每种星期先分到4次，再分配多出的连续几天。",
    "family": "整周与余日",
    "template": "整周与余日",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:018",
    "replacesUid": "hand100:018",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "周期",
    "t": "钩子",
    "s": "两项检查分别每隔4天、每隔6天进行一次（相邻两次日期相差4天、6天）。第1天同时检查，下次同时检查是第几天？",
    "o": [
      "12",
      "13",
      "24",
      "25"
    ],
    "a": 1,
    "e": "共同间隔lcm(4,6)=12天，从第1天再过12天是第13天。",
    "tr": "第12天是把间隔误当日期编号。",
    "signal": "公倍数算的是经过天数，日期编号还要加起点。",
    "family": "共同周期与日期编号",
    "template": "共同周期与日期编号",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:019",
    "replacesUid": "hand100:019",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "利润",
    "t": "钩子",
    "s": "商品每件成本80元，按成本加价25%定价，再按定价九折售出。每件利润多少元？",
    "o": [
      "0",
      "8",
      "10",
      "20"
    ],
    "a": 2,
    "e": "定价100，售价90，利润90−80=10。也可直接看1.25×0.9=1.125。",
    "tr": "25%−10%不是利润率，两个百分数基数不同。",
    "signal": "把连续变化写成倍率相乘。",
    "family": "加价折扣复合倍率",
    "template": "加价折扣复合倍率",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:020",
    "replacesUid": "hand100:020",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "利润",
    "t": "钩子",
    "s": "一种服务单价下降20%，要使总收入不变，服务次数需比原来增加百分之几？",
    "o": [
      "20",
      "30",
      "40",
      "25"
    ],
    "a": 3,
    "e": "新单价为原来4/5，次数须变为5/4，增加25%。",
    "tr": "价格降20%，数量增加20%仍会使收入下降。",
    "signal": "收入固定时，数量与单价成反比。",
    "family": "收入不变的反比例",
    "template": "收入不变的反比例",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:021",
    "replacesUid": "hand100:021",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "年龄",
    "t": "钩子",
    "s": "甲乙今年年龄之和54岁，6年前甲年龄是乙的2倍。按每过一年各增1岁计算，两人年龄差多少岁？",
    "o": [
      "14",
      "12",
      "18",
      "20"
    ],
    "a": 0,
    "e": "6年前总和54−12=42岁，按2∶1分为28和14；年龄差14岁始终不变。",
    "tr": "两个人倒推6年，总和应减12而不是6。",
    "signal": "不同年份先平移到同一年，年龄差不变。",
    "family": "时间平移与年龄差",
    "template": "时间平移与年龄差",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:022",
    "replacesUid": "hand100:022",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "浓度",
    "t": "钩子",
    "s": "10千克质量分数20%的盐水加入5千克纯水，充分混合且无损失。新盐水的盐质量分数为多少？",
    "o": [
      "1/10",
      "2/15",
      "1/5",
      "3/10"
    ],
    "a": 1,
    "e": "盐仍是10×20%=2千克，总质量15千克，浓度2/15。",
    "tr": "分母是混合后总质量，不是所加水量。",
    "signal": "加水只改变总质量，不改变溶质质量。",
    "family": "溶质守恒稀释",
    "template": "溶质守恒稀释",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:023",
    "replacesUid": "hand100:023",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "容斥",
    "t": "钩子",
    "s": "60人中参加甲项目的38人，参加乙项目的32人，两项都不参加的10人。两项都参加的有多少人？",
    "o": [
      "10",
      "12",
      "20",
      "22"
    ],
    "a": 2,
    "e": "至少参加一项的50人，38+32把交集多算一次，因此交集70−50=20。",
    "tr": "不能直接用38+32−60；60含两项都不参加者。",
    "signal": "先把全集换成真正的并集人数。",
    "family": "两集合与全不参加",
    "template": "两集合与全不参加",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:024",
    "replacesUid": "hand100:024",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "数列",
    "t": "钩子",
    "s": "某窗口连续7天每天办理量比前一天多3件，7天共140件。第7天办理多少件？",
    "o": [
      "20",
      "23",
      "26",
      "29"
    ],
    "a": 3,
    "e": "7天平均20件，就是第4天；第7天比第4天多3×3=9件，故29。",
    "tr": "从中间到最后只有3个间隔，不是7个。",
    "signal": "奇数项等差数列先锁中项，少设一个未知数。",
    "family": "等差对称中项",
    "template": "等差对称中项",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:025",
    "replacesUid": "hand100:025",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "余数",
    "t": "钩子",
    "s": "一批材料数量大于40且小于70，按每包6件或每包8件分装均余5件。共有多少件？",
    "o": [
      "53",
      "45",
      "48",
      "61"
    ],
    "a": 0,
    "e": "数量减5是6、8的公倍数，即24的倍数。区间内只有48+5=53。",
    "tr": "不能把数量本身当作24的倍数。",
    "signal": "两个余数相同，先统一减去余数。",
    "family": "同余转公共倍数",
    "template": "同余转公共倍数",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:026",
    "replacesUid": "hand100:026",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "总量差量",
    "t": "转化钩",
    "s": "甲乙丙丁四部门共240人，甲比丁多12人。乙调24人到丙后，其余乙人员全部并入丁，最终甲丙丁人数比为3∶3∶4。原乙多少人？",
    "o": [
      "36",
      "60",
      "48",
      "72"
    ],
    "a": 1,
    "e": "总数不变，最终甲72、丙72、丁96。原丁=72−12=60，乙并入丁36人，加调往丙的24人，原乙60人。",
    "tr": "最终丁96人不等于原丁；先借不变的甲倒推。",
    "signal": "部门虽合并，总人数和未变化部门仍可充当基准。",
    "family": "部门合并与总量守恒",
    "template": "部门合并与总量守恒",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:027",
    "replacesUid": "hand100:027",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "总量差量",
    "t": "转化钩",
    "s": "20人平均80分，去掉其中2人后其余18人平均81分。被去掉的2人平均多少分？",
    "o": [
      "70",
      "72",
      "71",
      "79"
    ],
    "a": 2,
    "e": "原总分1600，剩余1458，被去掉142分，平均71。也可看18人各高1分需由两人各少9分补平。",
    "tr": "平均数提高1，不代表去掉的人只低1分。",
    "signal": "均值升降必须配合剩余人数的权重。",
    "family": "剔除低分的均值变化",
    "template": "剔除低分的均值变化",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:028",
    "replacesUid": "hand100:028",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "经济",
    "t": "转化钩",
    "s": "30张参观票中，全价票40元、优惠票25元，合计990元。全价票有多少张？",
    "o": [
      "14",
      "15",
      "18",
      "16"
    ],
    "a": 3,
    "e": "假设全是25元票，费用750元；差额240元，每换一张全价多15元，故16张。",
    "tr": "用990÷40只给上界，不能得到实际张数。",
    "signal": "两类对象总数固定，先全假设为便宜的一类。",
    "family": "两档价格的差量方程",
    "template": "两档价格的差量方程",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:029",
    "replacesUid": "hand100:029",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "利润",
    "t": "转化钩",
    "s": "100件商品每件进价50元，其中80件以60元售出，余下20件以45元售出，不计其他费用。总利润多少元？",
    "o": [
      "700",
      "500",
      "600",
      "1000"
    ],
    "a": 0,
    "e": "前80件每件赚10元，共800；后20件每件亏5元，共亏100；总利润700。",
    "tr": "不能把60和45简单平均，两批数量不同。",
    "signal": "分批利润有正有负，用数量作权重求和。",
    "family": "分批销售加权总利",
    "template": "分批销售加权总利",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:030",
    "replacesUid": "hand100:030",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "工程",
    "t": "转化钩",
    "s": "甲单独12天、乙单独18天完成同一工程，效率恒定可相加。合作3天后乙离开，甲完成余下部分。总工期多少天？",
    "o": [
      "7",
      "10",
      "9",
      "12"
    ],
    "a": 1,
    "e": "总量36，合作3天做15，剩21由甲每天3完成需7天；总共3+7=10天。",
    "tr": "7天只是乙离开之后，不是总工期。",
    "signal": "分段先算剩余总量，注意问题的计时起点。",
    "family": "合作转单做",
    "template": "合作转单做",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:031",
    "replacesUid": "hand100:031",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "工程",
    "t": "转化钩",
    "s": "甲乙合作6天，甲丙合作8天，乙丙合作12天完成同一任务，各人效率恒定可相加。乙独做需多少天？",
    "o": [
      "12",
      "20",
      "16",
      "24"
    ],
    "a": 2,
    "e": "总量24，甲乙、甲丙、乙丙效率为4、3、2；乙效率=(4+2−3)/2=1.5，需16天。",
    "tr": "只相减会得到两个效率的差，不能直接当乙效率。",
    "signal": "相加两对再减第三对，留下目标人物的两倍效率。",
    "family": "成对效率反推个体",
    "template": "成对效率反推个体",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:032",
    "replacesUid": "hand100:032",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "工程",
    "t": "转化钩",
    "s": "空池进水管单开6小时注满，满池排水管单开12小时排空，流量恒定。两管同时开4小时后关闭排水管，继续进水。自开始共几小时注满？",
    "o": [
      "6",
      "10",
      "12",
      "8"
    ],
    "a": 3,
    "e": "前4小时净注入4×(1/6−1/12)=1/3池，剩2/3由进水管再用4小时注满，总8小时。",
    "tr": "进水和排水方向相反，净效率用减法。",
    "signal": "先合净流量，再按开关事件分段。",
    "family": "进排水分段净效率",
    "template": "进排水分段净效率",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:033",
    "replacesUid": "hand100:033",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "行程",
    "t": "转化钩",
    "s": "乙在甲前方300米处以4米/秒匀速前进。20秒后甲从原起点以6米/秒沿同向追赶。甲出发后多少秒追上乙？",
    "o": [
      "190",
      "150",
      "170",
      "210"
    ],
    "a": 0,
    "e": "甲启动时差距300+4×20=380米，速度差2米/秒，需190秒。",
    "tr": "300米是等待前的差距；也不要把等待20秒计入所问时间。",
    "signal": "把所有人平移到同一出发时刻，再做相对运动。",
    "family": "迟出发追及",
    "template": "迟出发追及",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:034",
    "replacesUid": "hand100:034",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "行程",
    "t": "转化钩",
    "s": "船在静水中的速度恒定，水速3千米/时。沿同一河段顺流用3小时、逆流用5小时。该河段长多少千米？",
    "o": [
      "30",
      "45",
      "36",
      "60"
    ],
    "a": 1,
    "e": "同程知顺逆速度比5∶3，两者差为2倍水速即6，故每份3；顺流15，路程45。",
    "tr": "顺逆流速度差是6，不是3。",
    "signal": "同路程时间比先反成速度比，再利用已知速度差。",
    "family": "顺逆流同程反推",
    "template": "顺逆流同程反推",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:035",
    "replacesUid": "hand100:035",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "行程",
    "t": "转化钩",
    "s": "汽车行驶150千米，前段50千米/时、后段75千米/时，全程不停留，共用2.5小时。前段长多少千米？",
    "o": [
      "50",
      "60",
      "75",
      "100"
    ],
    "a": 2,
    "e": "全按75行驶只需2小时，慢段多用0.5小时；每千米多用1/50−1/75=1/150小时，慢段75千米。",
    "tr": "2.5小时乘某一速度不能得到分段路程。",
    "signal": "把全程统一成快速度，额外时间只由慢段贡献。",
    "family": "分段速度与总用时",
    "template": "分段速度与总用时",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:036",
    "replacesUid": "hand100:036",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "极值",
    "t": "钩子",
    "s": "95箱物资需运送，每辆车最多装8箱，每辆只跑一趟，允许不满载。最少需几辆车？",
    "o": [
      "11",
      "13",
      "14",
      "12"
    ],
    "a": 3,
    "e": "11辆只能运88箱，不够；12辆可运96箱，足够。所求是95/8的向上取整。",
    "tr": "剩余7箱仍要占用一辆车，不能直接舍去余数。",
    "signal": "容量上限对应向上取整，先检验少一辆是否够。",
    "family": "容量取整",
    "template": "容量取整",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：只有容量向上取整，无第二约束。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:037",
    "replacesUid": "hand100:037",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "极值",
    "t": "钩子",
    "s": "某人5项考核总分410，每项得分都是0至90的整数。第5项最低可能得多少分？",
    "o": [
      "50",
      "40",
      "60",
      "80"
    ],
    "a": 0,
    "e": "要让第5项低，就让其余4项均取上限90：410−360=50；90、90、90、90、50可行。",
    "tr": "未要求各项分数互异，不要额外添加约束。",
    "signal": "目标最低，把其他部分推到允许的最高值。",
    "family": "总分与单项上限",
    "template": "总分与单项上限",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：其余四项取上限后一次相减，没有互异或名次耦合。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:038",
    "replacesUid": "hand100:038",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "排列",
    "t": "钩子",
    "s": "5名不同工作人员中选1名组长、1名副组长，二职不能兼任，甲不能任组长。共有多少种任命方式？",
    "o": [
      "12",
      "16",
      "20",
      "25"
    ],
    "a": 1,
    "e": "组长有除甲外4种，选定后副组长有4种，得16。",
    "tr": "岗位有名称，要计顺序；甲仍可以任副组长。",
    "signal": "先安排限制更多的岗位，再安排另一个。",
    "family": "有名岗位排除资格",
    "template": "有名岗位排除资格",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：先选有限制的组长，再选不同副手，是标准有名位置计数。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:039",
    "replacesUid": "hand100:039",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "组合",
    "t": "钩子",
    "s": "3名男生、3名女生中选3人，要求恰好2名女生。共有多少种选法？",
    "o": [
      "6",
      "12",
      "9",
      "18"
    ],
    "a": 2,
    "e": "先选女生C(3,2)=3种，再选男生3种，乘得9。",
    "tr": "恰好2名女生排除了3名女生，不是“至少”。",
    "signal": "互斥类别各选定数量，再乘法合并。",
    "family": "分类定额选择",
    "template": "分类定额选择",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：男女定额已经给定，按类别组合相乘，无禁配或条件样本耦合。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:040",
    "replacesUid": "hand100:040",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "排列",
    "t": "钩子",
    "s": "用1、2、3、4中的两个不同数字组成两位偶数，共有多少个？",
    "o": [
      "4",
      "8",
      "12",
      "6"
    ],
    "a": 3,
    "e": "个位只能2或4，共2种；十位可选剩余3个，共6个。",
    "tr": "个位占用的数字不能再作十位。",
    "signal": "能否为偶数只看个位，先处理限制位。",
    "family": "末位限制与不重复",
    "template": "末位限制与不重复",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：先选偶数个位，再选剩余十位，只有末位限制。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:041",
    "replacesUid": "hand100:041",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "概率",
    "t": "转化钩",
    "s": "4红球、3蓝球，等可能不放回抽2球。已知至少有1个红球，两球均红的概率是多少？",
    "o": [
      "1/3",
      "2/7",
      "3/7",
      "1/2"
    ],
    "a": 0,
    "e": "总共21对，扣除3对全蓝，条件样本空间18对；全红6对，概率6/18=1/3。",
    "tr": "条件已经排除全蓝，分母不能仍用21。",
    "signal": "先把已知条件当筛子，再在留下的情况里计数。",
    "family": "条件概率缩样本空间",
    "template": "条件概率缩样本空间",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:042",
    "replacesUid": "hand100:042",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "概率",
    "t": "转化钩",
    "s": "两枚公平六面骰独立掷出，已知点数不同，点数之和为8的概率是多少？",
    "o": [
      "1/9",
      "2/15",
      "1/6",
      "1/5"
    ],
    "a": 1,
    "e": "条件下36−6=30个等可能有序结果；和8且不同为(2,6)、(3,5)、(5,3)、(6,2)，概率4/30。",
    "tr": "不能保留(4,4)，也不能只记无序的两对。",
    "signal": "骰子可区分，先数有序结果再应用条件。",
    "family": "等可能有序对与条件",
    "template": "等可能有序对与条件",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:043",
    "replacesUid": "hand100:043",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "几何",
    "t": "转化钩",
    "s": "长12米、宽8米的长方形场地，沿内部四边修宽1米的步道，四角也计入步道。步道面积多少平方米？",
    "o": [
      "32",
      "40",
      "36",
      "44"
    ],
    "a": 2,
    "e": "外面积96，内部剩10×6=60，步道36。用外减内避免四角重复计数。",
    "tr": "周长40乘宽1会把四角多算4平方米。",
    "signal": "四边等宽区域，优先补成内外两个长方形。",
    "family": "均匀内边带面积",
    "template": "均匀内边带面积",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:044",
    "replacesUid": "hand100:044",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "几何",
    "t": "转化钩",
    "s": "两个圆柱容器高度相同，大容器半径是小容器2倍。用同一恒定体积流量水管，小容器9分钟注满，大容器从空到满需多少分钟？",
    "o": [
      "18",
      "27",
      "72",
      "36"
    ],
    "a": 3,
    "e": "高度相同，体积比为半径平方比4；流量相同，注满时间也为4倍，即36分钟。",
    "tr": "半径放大2倍，体积不是2倍；只有三维都放大才是8倍。",
    "signal": "先确认哪些维度变化，再把体积比转时间比。",
    "family": "体积比例与恒流时间",
    "template": "体积比例与恒流时间",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:045",
    "replacesUid": "hand100:045",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "几何",
    "t": "转化钩",
    "s": "三角形ABC面积96，D在AB上且AD∶DB=1∶2，E在AC上且AE∶EC=1∶3。三角形ADE面积是多少？",
    "o": [
      "8",
      "6",
      "12",
      "16"
    ],
    "a": 0,
    "e": "AD/AB=1/3，AE/AC=1/4，共角三角形面积比是两边比的乘积1/12，面积8。",
    "tr": "AD∶DB不是AD∶AB，分母要加上两段。",
    "signal": "共用夹角，无需相似也可用两邻边比相乘。",
    "family": "共角两边分点面积",
    "template": "共角两边分点面积",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:046",
    "replacesUid": "hand100:046",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "周期",
    "t": "转化钩",
    "s": "某月30天，其中星期一和星期二各有5天。以数字1至7依次表示星期一至星期日，该月最后一天的星期编号是多少？",
    "o": [
      "1",
      "2",
      "3",
      "7"
    ],
    "a": 1,
    "e": "30=4周+2天，多出的连续两天必为周一、周二，因此月初周一，月末周二。选项数字1至7依次代表周一至周日。",
    "tr": "不能任意放置第5个星期，余日必须连续。",
    "signal": "某星期出现5次，反推它是否属于月初那段余日。",
    "family": "星期次数反推月初",
    "template": "星期次数反推月初",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:047",
    "replacesUid": "hand100:047",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "周期",
    "t": "转化钩",
    "s": "某人按连续工作2天、休息1天循环，统计期第1天是一个循环的首个工作日。工作日每天办理10件。前17天共办理多少件？",
    "o": [
      "100",
      "110",
      "120",
      "130"
    ],
    "a": 2,
    "e": "17=5×3+2，5轮工作10天，余下2天也工作，共12天，办120件。",
    "tr": "余下2天不是按2/3折算，而要按周期起点逐天补。",
    "signal": "完整周期算总数，余段按真实顺序补。",
    "family": "工作休息余段",
    "template": "工作休息余段",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:048",
    "replacesUid": "hand100:048",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "利润",
    "t": "转化钩",
    "s": "一次活动固定支出300元，每接待1人另支出20元，向每人收费35元。所有人数均为整数。至少接待多少人才开始盈利？",
    "o": [
      "20",
      "22",
      "30",
      "21"
    ],
    "a": 3,
    "e": "每人贡献15元覆盖固定支出，20人恰好收支相抵；盈利要严格大于0，故至少21人。",
    "tr": "收支相抵不是盈利，注意严格不等号。",
    "signal": "先把单价减可变成本，再判断盈亏临界点。",
    "family": "固定成本与严格盈利",
    "template": "固定成本与严格盈利",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:049",
    "replacesUid": "hand100:049",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "浓度",
    "t": "转化钩",
    "s": "100千克20%的盐水加纯水稀释为16%，无损失。需加多少千克水？",
    "o": [
      "25",
      "20",
      "30",
      "40"
    ],
    "a": 0,
    "e": "盐仍20千克，目标总质量20÷16%=125千克，需加25千克水。",
    "tr": "125是最终总质量，不是加水量。",
    "signal": "溶质守恒先反推最终总量，再减原量。",
    "family": "目标浓度反推加水",
    "template": "目标浓度反推加水",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:050",
    "replacesUid": "hand100:050",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "余数",
    "t": "转化钩",
    "s": "某批材料数量大于50，除以5余2，除以7余3。数量最少为多少？",
    "o": [
      "57",
      "52",
      "62",
      "67"
    ],
    "a": 1,
    "e": "满足两余数的数为17+35k；大于50的最小值52。也可从最小选项起检验，52同时满足两式。",
    "tr": "找到17只是首个解，尚未满足大于50的范围。",
    "signal": "先合并同余，再用区间选择对应的那一支。",
    "family": "异余数与下界",
    "template": "异余数与下界",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:051",
    "replacesUid": "hand100:051",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "总量差量",
    "t": "二步钩",
    "s": "甲乙共50人，甲平均82分、乙76分，总平均79.6分。现甲调10人到乙，这10人平均80分。调动后乙平均多少分？",
    "o": [
      "76",
      "78",
      "232/3",
      "80"
    ],
    "a": 2,
    "e": "甲占(79.6−76)/(82−76)=3/5，即30人，乙20人。新乙总分20×76+10×80=2320，人数30，均分232/3。",
    "tr": "调来者平均80，不等于原甲全体平均82。",
    "signal": "先用均值差求人数比，再按真实转移总分更新。",
    "family": "两组均值与调人均值",
    "template": "两组均值与调人均值",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:052",
    "replacesUid": "hand100:052",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "比例",
    "t": "转化钩",
    "s": "甲乙人数原比5∶4，从甲调8人到乙后两队人数相同。两队原来共多少人？",
    "o": [
      "72",
      "128",
      "160",
      "144"
    ],
    "a": 3,
    "e": "调8人让人数差减少16，原相差1份就是16人，共9份=144人。",
    "tr": "单向调动使双方差减少两倍调动量，而非8。",
    "signal": "转移问题先看差量缩减，而不逐队设两个未知数。",
    "family": "双边转移的差量",
    "template": "双边转移的差量",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：调8人使人数差减少16，单一差量模型即可锁一份和总人数。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:053",
    "replacesUid": "hand100:053",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "利润",
    "t": "转化钩",
    "s": "100件商品成本均为40元，先以60元售出20件。其余80件按同一价格售出，且单价为整数。要使总利润不少于1200元，余货单价最低多少元？",
    "o": [
      "50",
      "45",
      "48",
      "55"
    ],
    "a": 0,
    "e": "目标总收入至少5200元，已收入1200，余货至少收入4000；80件每件至少50。",
    "tr": "1200是利润目标，不是总收入目标；还要覆盖4000元成本。",
    "signal": "把利润下界先转成总收入下界，再扣已完成部分。",
    "family": "分批保利的价格边界",
    "template": "分批保利的价格边界",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：利润目标转总收入后扣已售收入，余货单价下界恰为整数，无额外搜索。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:054",
    "replacesUid": "hand100:054",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "工程",
    "t": "二步钩",
    "s": "同一工程甲独做20天、乙独做30天完成，起初效率恒定可相加。合作3天后乙退出，甲效率提高50%并保持至完工。总工期多少天？",
    "o": [
      "10",
      "13",
      "12",
      "15"
    ],
    "a": 1,
    "e": "前3天完成3×(1/20+1/30)=1/4，剩3/4；甲新效率3/40，余工需10天，总13天。",
    "tr": "效率提高50%不是工期减少50%，还要分清总工期和剩余工期。",
    "signal": "事件前后效率不同，守住剩余工作量再换新效率。",
    "family": "退出与留守效率提升",
    "template": "退出与留守效率提升",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:055",
    "replacesUid": "hand100:055",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "工程",
    "t": "二步钩",
    "s": "甲独做12天、乙独做18天完成工程，两人效率恒定。按甲1天、乙1天轮流，甲先做，最后一天可只做所需时长。共需多少天？",
    "o": [
      "14",
      "15",
      "43/3",
      "16"
    ],
    "a": 2,
    "e": "设总量36，每轮2天做5。7轮14天做35，余1由甲每天3完成，需1/3天，总43/3。",
    "tr": "不能把最后的1/3天向上取整，题目允许不足一天。",
    "signal": "先按完整轮次装满，再由下一位接手尾量。",
    "family": "轮流作业的末日分数",
    "template": "轮流作业的末日分数",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:056",
    "replacesUid": "hand100:056",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "行程",
    "t": "二步钩",
    "s": "甲乙从直路两端A、B同时相向匀速出发，到端点立刻折返、不停留。首次相遇点距A为150米，第二次相遇点距B为100米，且第二次相遇前两人都已各折返一次。AB长多少米？",
    "o": [
      "250",
      "300",
      "400",
      "350"
    ],
    "a": 3,
    "e": "两次相遇时合走路程分别为1倍、3倍全长，故甲第二次累计450米；甲已到B再返回100米，得全长450−100=350。",
    "tr": "第二次甲的路程是全长加100，不是全长减100。",
    "signal": "相遇次数转总路程倍数，再追踪同一个人的路程。",
    "family": "往返第二次相遇",
    "template": "往返第二次相遇",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:057",
    "replacesUid": "hand100:057",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "行程",
    "t": "二步钩",
    "s": "600米环道上，甲乙从同一点同时同向匀速跑，速度5、3米/秒。60秒后乙立即反向，甲不变。自乙转向起再过多少秒二人首次相遇？",
    "o": [
      "60",
      "15",
      "40",
      "75"
    ],
    "a": 0,
    "e": "转向时甲领先120米；两人沿新方向靠近的那段弧长为600−120=480米，速度和8，需60秒。",
    "tr": "直接120÷8会沿错误的弧判断相向接近。",
    "signal": "转向前先标位置，转向后重选将被消耗的相对路程。",
    "family": "环道转向后的相对位置",
    "template": "环道转向后的相对位置",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:058",
    "replacesUid": "hand100:058",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "行程",
    "t": "二步钩",
    "s": "A、B相距420千米。甲从A以60千米/时出发，1小时后乙从B以80千米/时向A出发，均匀速不停留。自甲出发至相遇共多少小时？",
    "o": [
      "18/7",
      "25/7",
      "3",
      "4"
    ],
    "a": 1,
    "e": "乙启动时余距360，两人再用360/140=18/7小时相遇；加甲先行1小时，共25/7。",
    "tr": "18/7只计乙出发后的时间。",
    "signal": "统一到晚出发时刻解相遇，最后还原问的计时起点。",
    "family": "异时出发相向",
    "template": "异时出发相向",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:059",
    "replacesUid": "hand100:059",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "极值",
    "t": "转化钩",
    "s": "50人分成5组，每组至少3人，人数两两不同。人数最多的一组最多可有多少人？",
    "o": [
      "26",
      "30",
      "32",
      "35"
    ],
    "a": 2,
    "e": "要让最大组尽可能多，其他4组取最小互异人数3、4、5、6，共18，余32，且32不与它们重复。",
    "tr": "给其他4组都分3人违反互异条件。",
    "signal": "上界来自其他组的最小占用，还要检查目标组不冲突。",
    "family": "互异下限与最大单组",
    "template": "互异下限与最大单组",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：其余四组取最小互异人数，剩余归目标组，是一层边界构造。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:060",
    "replacesUid": "hand100:060",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "入门",
    "h": "极值",
    "t": "钩子",
    "s": "袋中4种颜色球各10个，逐个不放回取球。至少取多少个才能保证某一种颜色已有3个？",
    "o": [
      "8",
      "10",
      "12",
      "9"
    ],
    "a": 3,
    "e": "不出现3个同色时，每种最多取2个，共8个；第9个必使某色到3个，且各色库存足够支持最坏情况。",
    "tr": "不是要求每一种都有3个，也不是只需两个同色。",
    "signal": "先算在禁止目标事件时最多能取多少。",
    "family": "抽屉容量保证三同色",
    "template": "抽屉容量保证三同色",
    "cost": "低",
    "targetSeconds": 35,
    "difficultyBasis": "一个主要关系，识别后一步收口；本题：每色先取2再多取1，是标准抽屉保证模型。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:061",
    "replacesUid": "hand100:061",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "组合",
    "t": "二步钩",
    "s": "12份相同物资全部分给甲乙丙三个有名部门，每部门至少2份，且甲最多5份。各部门所得份数允许相同；只要至少一个部门所得份数发生变化，就视为不同分配方案。共有多少种？",
    "o": [
      "22",
      "18",
      "20",
      "28"
    ],
    "a": 0,
    "e": "按甲拿2、3、4、5分类，乙丙各至少2份，分别有7、6、5、4种，合22。部门有名称，但所得份数允许相同，不额外添加互异条件。",
    "tr": "物资相同但部门有名称，按谁拿多少区分方案；允许同份数，不能误加三部门份数互异的条件（那会变为14种）。",
    "signal": "先枚举有上界的甲，再用总量确定乙丙；部门有名不等于所得份数必须互异。",
    "family": "有名整数分配与上界",
    "template": "有名整数分配与上界",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:062",
    "replacesUid": "hand100:062",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "组合",
    "t": "二步钩",
    "s": "从甲乙丙丁及另3人共7名不同人员中选4人。甲乙恰好选1人，丙丁不能同时入选。共有多少种选法？",
    "o": [
      "12",
      "14",
      "18",
      "20"
    ],
    "a": 1,
    "e": "甲乙选谁有2种；其余5人选3，排除丙丁同时在内的3种，得2×[C(5,3)−3]=14。",
    "tr": "“恰好1人”既不允许都选，也不允许都不选。",
    "signal": "先消去恰选约束，再对剩余禁配用补集。",
    "family": "恰选一人与禁止同选耦合",
    "template": "恰选一人与禁止同选耦合",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:063",
    "replacesUid": "hand100:063",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "组合状态",
    "t": "二步钩",
    "s": "6天每天由甲或乙值班，各值3天。要求任一天结束时，甲累计值班天数都不少于乙。共有多少种值班序列？",
    "o": [
      "4",
      "6",
      "5",
      "10"
    ],
    "a": 2,
    "e": "记甲+1、乙−1，起点0且前缀和不负。全部C(6,3)=20条，反射越界前缀得到坏路径C(6,2)=15条，合法5条；也可逐日按余额递推。",
    "tr": "只保证最终各3天不够，中间不能乙领先。",
    "signal": "累计领先限制是路径边界，不是普通选3天。",
    "family": "均衡路径不越界",
    "template": "均衡路径不越界",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:064",
    "replacesUid": "hand100:064",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "组合状态",
    "t": "二步钩",
    "s": "5道判断题，从0分起，答对加1分、答错扣1分，要求每道答完后得分都严格大于0。不限制最终得分，共有多少种对错序列？",
    "o": [
      "5",
      "10",
      "16",
      "6"
    ],
    "a": 3,
    "e": "首题必须对，扣去首题的1分后，余4步是从0出发的非负路径。逐步状态计数为{1:1}、{0:1,2:1}、{1:2,3:1}、{0:2,2:3,4:1}，共6种。",
    "tr": "严格正与非负不同；只锁首题会错算16，未检查后续越界。",
    "signal": "先用强制首步平移边界，再递推所有可能终点。",
    "family": "严格领先且终点不限",
    "template": "严格领先且终点不限",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:065",
    "replacesUid": "hand100:065",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "概率",
    "t": "二步钩",
    "s": "5红球、3蓝球，等可能不放回抽3球。至少有2个红球的概率是多少？",
    "o": [
      "5/7",
      "5/14",
      "1/2",
      "3/4"
    ],
    "a": 0,
    "e": "有利为2红1蓝或3红：C(5,2)×3+C(5,3)=40；总C(8,3)=56，得5/7。",
    "tr": "至少2红包括3红，两类互斥才能相加。",
    "signal": "按红球数量分层，选取用组合数而非顺序乘法。",
    "family": "多类别至少数量",
    "template": "多类别至少数量",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:066",
    "replacesUid": "hand100:066",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "概率",
    "t": "二步钩",
    "s": "等可能选择甲、乙两盒之一，甲盒2红1蓝，乙盒1红3蓝；盒内各球等可能取出1个。已知取到红球，它来自甲盒的概率是多少？",
    "o": [
      "1/2",
      "8/11",
      "2/3",
      "3/4"
    ],
    "a": 1,
    "e": "两盒取红的权重为(1/2)(2/3)与(1/2)(1/4)，同比放大成8∶3，所以来自甲的概率8/11。",
    "tr": "不能把两盒合并成3红4蓝，因为先等可能选盒而非选球。",
    "signal": "条件改变来源权重，用先验×事件概率重新归一化。",
    "family": "来源后验概率",
    "template": "来源后验概率",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:067",
    "replacesUid": "hand100:067",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "几何",
    "t": "二步钩",
    "s": "三角形ABC面积80，D是AB中点，E在AC上且AE∶EC=1∶2，BE与CD交于P。三角形BDP面积多少？",
    "o": [
      "10",
      "12",
      "8",
      "16"
    ],
    "a": 2,
    "e": "面积比不受仿射变换影响，可设A(0,0)、B(6,0)、C(0,6)，则D(3,0)、E(0,2)。联立BE的x+3y=6和CD的2x+y=6得P高6/5；BDP与ABC面积比=(3×6/5)/(6×6)=1/10，故8。",
    "tr": "两条分线一般不交于中点；要先求交点相对高度。",
    "signal": "只问面积比，可用方便坐标保留分点比例，不必求真实边长。",
    "family": "双分线交点的仿射面积",
    "template": "双分线交点的仿射面积",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:068",
    "replacesUid": "hand100:068",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "几何",
    "t": "转化钩",
    "s": "边长6厘米的实心正方体，沿平行于某个面的平面切成两块，厚度分别2和4厘米。不计切割损耗，两块表面积之和多少平方厘米？",
    "o": [
      "216",
      "252",
      "324",
      "288"
    ],
    "a": 3,
    "e": "原表面积216，每块各新增一个6×6截面，共增加72，合288。厚度只保证确实切成两块，不影响新增截面。",
    "tr": "只加一个截面会漏掉另一块的新面。",
    "signal": "切开使原来内部的一张面暴露两次。",
    "family": "切割新增截面",
    "template": "切割新增截面",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：一个切面暴露两次，切块厚度不引入新约束。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:069",
    "replacesUid": "hand100:069",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "熟练",
    "h": "几何",
    "t": "转化钩",
    "s": "半径3厘米、高8厘米的实心圆柱，熔铸成半径2厘米、高6厘米的实心圆锥，不计损耗，最多能铸成几个完整圆锥？",
    "o": [
      "9",
      "6",
      "8",
      "12"
    ],
    "a": 0,
    "e": "圆柱体积72π，每个圆锥体积(1/3)π×4×6=8π，恰为9个。",
    "tr": "圆锥体积要除以3；求个数时π可整体约掉。",
    "signal": "材质不变且无损耗，只守恒体积，不守恒表面积。",
    "family": "熔铸体积守恒",
    "template": "熔铸体积守恒",
    "cost": "中",
    "targetSeconds": 55,
    "difficultyBasis": "两步转换或一个明确边界；本题：一个体积守恒模型，直接用圆柱圆锥的体积比，π不增加耦合。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:070",
    "replacesUid": "hand100:070",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "周期",
    "t": "二步钩",
    "s": "某31天月份中，星期一、星期二、星期三的总天数为15。这个月第一个星期五是几号？",
    "o": [
      "3",
      "5",
      "4",
      "6"
    ],
    "a": 1,
    "e": "三种星期每种最多5次，总15说明都为5次。31天余3天恰为周一二三，故1日周一，第一个周五5日。",
    "tr": "三种星期合计15，不是每种15；也不能忽略余日连续性。",
    "signal": "计数达到共同上界时，每个分量都必须取到上界。",
    "family": "三种星期计数联合",
    "template": "三种星期计数联合",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:071",
    "replacesUid": "hand100:071",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "周期",
    "t": "二步钩",
    "s": "两项巡检分别每6天、每8天一次，第1天同检。下次既同检、又与第1天同为一个星期几，是第几天？",
    "o": [
      "25",
      "49",
      "169",
      "168"
    ],
    "a": 2,
    "e": "同时满足经过天数是6、8、7的倍数，最小168；日期编号为169。",
    "tr": "24天只满足同检，不保证星期相同。",
    "signal": "把星期约束也作为周期加入最小公倍数。",
    "family": "共同周期与同星期",
    "template": "共同周期与同星期",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:072",
    "replacesUid": "hand100:072",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "周期",
    "t": "二步钩",
    "s": "甲按工作3天休息1天循环，乙按工作2天休息1天循环，两人第1天均为各自循环的首个工作日。前12天两人同时工作的有几天？",
    "o": [
      "5",
      "7",
      "8",
      "6"
    ],
    "a": 3,
    "e": "周期4与3互质，12天覆盖完整共同周期，各种相位配对恰出现一次，可直接算12×3/4×2/3=6。也可容斥：甲休3天、乙休4天，共同休1天，同工作12−3−4+1=6。",
    "tr": "不能对任意周期、任意窗口无条件相乘；本题周期互质且窗口是完整共同周期，比例乘法成立。周期不互质或窗口不完整时，需核对相位与余段。",
    "signal": "先查周期是否互质、窗口是否完整；满足时比例乘法可直算，否则检查相位、用逐日或容斥计数。",
    "family": "两个出勤周期交集",
    "template": "两个出勤周期交集",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:073",
    "replacesUid": "hand100:073",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "利润",
    "t": "二步钩",
    "s": "商品每件成本20元，售价50元时日销100件；每降价2元，日销量增加20件，且只允许降价0至10次，次数为整数。销量均能售完，无其他费用。最大日利润多少元？",
    "o": [
      "4000",
      "3000",
      "3600",
      "4200"
    ],
    "a": 0,
    "e": "降k次利润=(30−2k)(100+20k)=4000−40(k−5)²。k=5可取且满足范围，最大4000。",
    "tr": "优化的是利润而非营业额；降价既改变数量也改变单件利润。",
    "signal": "线性价量变化相乘成二次式，配方后检查整数与边界。",
    "family": "整数降价的二次收益",
    "template": "整数降价的二次收益",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:074",
    "replacesUid": "hand100:074",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "极值",
    "t": "二步钩",
    "s": "大车每辆运8箱、租金500元，小车每辆运5箱、租金350元。运41箱，每车只跑一趟，允许不满载，两种车数量不限。最低租金多少元？",
    "o": [
      "2650",
      "2700",
      "2750",
      "2850"
    ],
    "a": 1,
    "e": "按大车0至6辆，配足最少小车，费用依次3150、2950、2750、2900、2700、2850、3000。4大2小运42箱，2700最低；超过6辆大车已不划算。",
    "tr": "单箱便宜不代表只租大车最省，尾量装载和整数辆数会改变结果。",
    "signal": "固定一类车，另一类直接向上取整，枚举范围有限。",
    "family": "混合运力整数成本",
    "template": "混合运力整数成本",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:075",
    "replacesUid": "hand100:075",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "浓度",
    "t": "二步钩",
    "s": "100千克20%的盐水，先充分混匀取出20千克并补20千克纯水；再混匀取出20千克，补入20千克40%的盐水。无损失，最终质量分数百分之几？",
    "o": [
      "16",
      "20",
      "20.8",
      "24"
    ],
    "a": 2,
    "e": "第一次盐剩20×0.8=16千克；第二次剩16×0.8=12.8，再添20×0.4=8，共20.8千克，总量100，浓度20.8%。",
    "tr": "第二次取出的已是16%盐水，不能仍按原20%计算。",
    "signal": "每次取走等比例溶质，按顺序更新，不把两次独立看待。",
    "family": "两次置换的乘法保留",
    "template": "两次置换的乘法保留",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:076",
    "replacesUid": "hand100:076",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "总量差量",
    "t": "综合建模",
    "s": "甲乙丙人数比1∶2∶3，甲平均80分，丙平均90分。丙调10人到甲，这10人平均92分，调后甲平均86分。调后丙平均多少分？",
    "o": [
      "88",
      "90",
      "91",
      "89"
    ],
    "a": 3,
    "e": "设原甲x人，(80x+920)/(x+10)=86，得x=10。丙原30人总2700分，调出920后余20人，平均1780/20=89。",
    "tr": "先验人数比作用于调动前；丙调出者的92分不能换成丙平均90。",
    "signal": "用一个部门的均值变化锁人数尺度，再回到另一个部门做总量扣减。",
    "family": "人数比例与转移均分反推",
    "template": "人数比例与转移均分反推",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:077",
    "replacesUid": "hand100:077",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "比例",
    "t": "二步钩",
    "s": "甲乙丙共180人，先把甲的1/4调给乙，再把此时乙的1/7调给丙。最终甲乙丙人数比1∶2∶3。原乙有多少人？",
    "o": [
      "60",
      "50",
      "70",
      "80"
    ],
    "a": 0,
    "e": "最终30、60、90。倒推第二步：乙此前70，调出10；倒推第一步：甲原40，调出10，故原乙70−10=60。",
    "tr": "第二步的1/7以接收甲人员后的乙为基数。",
    "signal": "顺序倍率操作适合逆推，每一步恢复当时的基数。",
    "family": "顺序转移与最终比例逆推",
    "template": "顺序转移与最终比例逆推",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：两次比例操作改变中间基数，逆序恢复即可，属于多事件比例深化。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:078",
    "replacesUid": "hand100:078",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "工程",
    "t": "综合建模",
    "s": "工程分先后两个阶段，每阶段36单位。第一阶段甲每天3单位、乙2单位；第二阶段甲每天1.5单位、乙3单位。甲第0天开工，乙第2天加入，此后两人一直合作，第一阶段完立即进入第二阶段，允许不足整天。总共多少天完成？",
    "o": [
      "14",
      "16",
      "15",
      "18"
    ],
    "a": 1,
    "e": "甲前2天做6，首阶段余30由合效率5再做6天，首阶段第8天结束；次阶段合效率4.5，36÷4.5=8天，总16。",
    "tr": "不能把两阶段72单位除以同一个合效率，也不能把乙晚到再额外重复加一次。",
    "signal": "迟到和阶段切换是两个不同事件，分段守恒才不重复计时。",
    "family": "迟到与阶段效率切换",
    "template": "迟到与阶段效率切换",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:079",
    "replacesUid": "hand100:079",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "工程",
    "t": "综合建模",
    "s": "两台机器恒定效率分别为每小时6、4单位。任务X需24单位、Y需20单位。同一任务同一时刻最多由一台机器加工；机器可随时换任务，任务允许中断续做、无切换损失。两台同时启动，全部完成最少多少小时？",
    "o": [
      "4",
      "24/5",
      "22/5",
      "5"
    ],
    "a": 2,
    "e": "总量44、总效率10给下界4.4小时。前3.2小时快机做X、慢机做Y；后1.2小时交换，X完成19.2+4.8=24，Y完成12.8+7.2=20，下界可达。",
    "tr": "只把两任务固定分给两机得5小时；但不能只写44/10而不验证“同任务不可同时加工”。",
    "signal": "先取全系统容量下界，再构造满足资源冲突的排程。",
    "family": "并行任务与可抢占换机",
    "template": "并行任务与可抢占换机",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:080",
    "replacesUid": "hand100:080",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "工程",
    "t": "综合建模",
    "s": "三项目分别需20、26、28单位工作量。甲组每天6单位、乙组每天4单位，每组每天只能服务一个项目，可在次日换项目；两组可同日服务同一项目。每组按整天派工，完成后当天余力不能转用。最少几天全完？",
    "o": [
      "7",
      "9",
      "10",
      "8"
    ],
    "a": 3,
    "e": "总74单位、每天最多10，至少8天。给三项目分别配置甲2、3、2个工作日，乙2、2、4个工作日，恰完成20、26、28；甲共7日乙8日，可排在8日内。",
    "tr": "总量下界未必可达，必须同时检查整日配置和两个组各自可用天数。",
    "signal": "容量下界搭配整数资源分配，找一组可行构造就能封住最优值。",
    "family": "整日派工与容量可行构造",
    "template": "整日派工与容量可行构造",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:081",
    "replacesUid": "hand100:081",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "行程",
    "t": "综合建模",
    "s": "600米环道上，甲乙从同一起点同向出发，速度6、4米/秒；丙同时从沿跑向前方300米处同向出发，速度3米/秒。速度恒定，三人首次同时位于同一点是出发后多少秒？",
    "o": [
      "300",
      "100",
      "200",
      "600"
    ],
    "a": 0,
    "e": "甲乙重合要求2t为600倍数，故t是300倍数；甲丙重合要求3t−300为600倍数。最小正候选t=300同时满足，故300。",
    "tr": "只比较任意一对会得到100或200等不能三人同时成立的时刻。",
    "signal": "多个相遇条件共用同一个时间，先用最稀疏的一对筛候选。",
    "family": "多相对位置的同余交集",
    "template": "多相对位置的同余交集",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:082",
    "replacesUid": "hand100:082",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "行程",
    "t": "二步钩",
    "s": "汽车去程60千米/时、返程40千米/时，到目的地停留半小时后原路返回。全程连停留不超过4小时。去程每千米耗油0.10升、返程0.08升，可用油14.4升。最多能到距出发点多少千米处？",
    "o": [
      "72",
      "80",
      "84",
      "96"
    ],
    "a": 1,
    "e": "时间限制给D(1/60+1/40)≤3.5，D≤84；油量限制0.18D≤14.4，D≤80。取更紧的80，且用时10/3+1/2<4，确实可行。",
    "tr": "不能只算时间上限84；去返耗油都要计入同一单程距离。",
    "signal": "多个预算同时限制同一目标，分别求上界再取最小并验证。",
    "family": "时间与燃料双预算",
    "template": "时间与燃料双预算",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：两个线性预算直接给同一距离的上界，取小并验证，没有整数资源配置。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:083",
    "replacesUid": "hand100:083",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "极值",
    "t": "综合建模",
    "s": "生产A、B两种产品，A每件用2单位材料、3小时，利润70元；B每件用3单位材料、2小时，利润80元。材料最多30单位、工时最多29小时，件数为非负整数。最大利润多少元？",
    "o": [
      "830",
      "840",
      "850",
      "890"
    ],
    "a": 2,
    "e": "设B为y件。y≥8时由材料约束得利润≤1050−25y≤850；y≤5时由工时约束得利润≤(2030+100y)/3<850。只查y=6、7分别最多830、840。A3件B8件可赚850，满足两资源限制。",
    "tr": "两条边界的实数交点可能不是整数方案；890只是松上界。",
    "signal": "用不同资源在不同区间压上界，把大枚举压成两种边界情况。",
    "family": "整数生产资源与分段上界",
    "template": "整数生产资源与分段上界",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:084",
    "replacesUid": "hand100:084",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "极值",
    "t": "二步钩",
    "s": "6人考试成绩为0至100的互异整数，总分550。某人得90分，按分数从高到低排名，他最低可能排第几名？",
    "o": [
      "3",
      "4",
      "6",
      "5"
    ],
    "a": 3,
    "e": "若第6名，其余5人至少91至95，总分至少90+465=555，矛盾。第5名可取89、90、91、92、93、95，和550，故第5。",
    "tr": "分数互异带来递增下界，不能把5个高于90者全设91。",
    "signal": "名次最差等价于高分者最多，先构造高分组的最小总分。",
    "family": "互异分数与最低名次",
    "template": "互异分数与最低名次",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：固定目标分数，用高分组最低总和排除最差名次，再给可行构造。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:085",
    "replacesUid": "hand100:085",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "极值",
    "t": "二步钩",
    "s": "30人全部分4组，人数为互异正整数，最大组人数恰为最小组的2倍。最小组人数最大可能是多少？",
    "o": [
      "5",
      "4",
      "6",
      "7"
    ],
    "a": 0,
    "e": "设最小m，另两组至少m+1、m+2，最大2m，故总量至少5m+3≤30，m≤5。5、6、9、10满足总量和倍数关系，所以5可达。",
    "tr": "只按平均数30/4会漏掉互异和最大倍数共同消耗的容量。",
    "signal": "先把端点倍数嵌入最小序列，再用总和封上界并构造。",
    "family": "互异人数与倍数端点",
    "template": "互异人数与倍数端点",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：互异和倍数可压入同一最小人数变量，得到单一总量上界后构造。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:086",
    "replacesUid": "hand100:086",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "组合",
    "t": "综合建模",
    "s": "7名不同人员分到第1、2、3天，分别3人、2人、2人。甲固定在第1天，乙丙不能在同一天。共有多少种安排？",
    "o": [
      "48",
      "72",
      "60",
      "84"
    ],
    "a": 1,
    "e": "若乙丙恰有1人与甲同日：2×4种选首日余员，余4人分后两日6种，得48。若两人都不在首日：首日另选2人6种，后两日必须拆乙丙，各配另1人有4种，得24。合72。",
    "tr": "天数有名称，不能除以2；乙丙也可能有1人在首日，不能只数都留在后两日。",
    "signal": "先按受限人物落在哪一组分类，组内不计顺序、组间有标签。",
    "family": "有名分组与固定成员禁同组",
    "template": "有名分组与固定成员禁同组",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:087",
    "replacesUid": "hand100:087",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "排列",
    "t": "综合建模",
    "s": "甲乙丙丁戊己6人排一列，甲必须在乙前面（不必相邻），丙丁不能相邻，戊不能在两端。共有多少种排法？",
    "o": [
      "144",
      "192",
      "168",
      "240"
    ],
    "a": 2,
    "e": "先不管甲乙先后：丙丁不邻共720−2×120=480；其中戊在两端共2×(120−2×24)=144，剩336。交换甲乙不改变其余限制，恰一半满足甲在乙前，得168。",
    "tr": "甲在乙前不是甲乙相邻；最后除2需确认交换甲乙保留另外两项限制。",
    "signal": "先用补集处理位置限制，再利用标签交换的对称性。",
    "family": "相对次序与非邻接非端点",
    "template": "相对次序与非邻接非端点",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:088",
    "replacesUid": "hand100:088",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "组合状态",
    "t": "综合建模",
    "s": "8天每日收入或支出1单位，从0开始，每日结束余额都不负，8天共收入4次、支出4次，且第4天结束余额为2。共有多少种收支序列？",
    "o": [
      "6",
      "8",
      "14",
      "9"
    ],
    "a": 3,
    "e": "前4步须3次收入1次支出且不负，支出可在第2、3、4步，共3种。后4步从2回0，须1入3出，收入不能最后发生，可在前3步，共3种；合9。",
    "tr": "不能直接套8步卡特兰数14，因为还有限定中途余额。",
    "signal": "按指定中间状态拆开路径，两段各守边界再相乘。",
    "family": "不越界与中途余额",
    "template": "不越界与中途余额",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:089",
    "replacesUid": "hand100:089",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "概率",
    "t": "综合建模",
    "s": "有标号1至6的6张卡，等可能不放回抽3张。已知至少含1张偶数卡，抽到的最大标号为5且三张标号和为偶数的概率是多少？",
    "o": [
      "4/19",
      "1/5",
      "5/19",
      "1/4"
    ],
    "a": 0,
    "e": "条件样本为C(6,3)−1=19种（只去掉1、3、5）。最大5要含5且另选自1至4，和为偶数要求另两张一奇一偶，有2×2=4种，故4/19。",
    "tr": "不能以20作分母；含5后另两张之和要为奇数才使总和偶。",
    "signal": "先缩条件空间，再把最大值固定、奇偶约束转分类选择。",
    "family": "条件抽样与最大值奇偶",
    "template": "条件抽样与最大值奇偶",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:090",
    "replacesUid": "hand100:090",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "概率",
    "t": "综合建模",
    "s": "等可能选甲、乙盒之一。甲盒2红2蓝，乙盒3红1蓝；选定后连续等可能不放回抽2球。已知第1球为红，第2球也为红的概率是多少？",
    "o": [
      "1/2",
      "8/15",
      "3/5",
      "2/3"
    ],
    "a": 1,
    "e": "第一红使来源权重甲∶乙=2∶3；之后甲再红1/3，乙再红2/3，所求(2/5)(1/3)+(3/5)(2/3)=8/15。",
    "tr": "已知首红后不能仍按两盒各1/2加权，且各盒红球数已减1。",
    "signal": "先更新来源权重，再在每个来源内部更新不放回概率。",
    "family": "后验来源与不放回续抽",
    "template": "后验来源与不放回续抽",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:091",
    "replacesUid": "hand100:091",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "几何",
    "t": "综合建模",
    "s": "容器下部为高9厘米的倒立圆锥，上部为同底面半径的圆柱。空容器以恒定体积流量注水，1分钟液面高3厘米，从开始共81分钟注满。容器总高多少厘米？",
    "o": [
      "12",
      "18",
      "15",
      "27"
    ],
    "a": 2,
    "e": "锥内液面高度为锥高1/3，体积占1/27，故注满锥需27分钟；圆柱再注54分钟，其体积是锥的2倍，同底面积下圆柱高为2×9/3=6，总高15。",
    "tr": "锥内液面高度不随时间线性增长；81分钟含最初1分钟。",
    "signal": "先用相似体积的立方比锁满锥时间，再把余水量换柱高。",
    "family": "圆锥液面立方与圆柱接续",
    "template": "圆锥液面立方与圆柱接续",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:092",
    "replacesUid": "hand100:092",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "几何",
    "t": "综合建模",
    "s": "直角三角形ABC中∠C=90°，高CD垂直AB，AD=9米、DB=16米。过CD中点作AB平行线交AC、BC，截出不含C的梯形。该梯形周长多少米？",
    "o": [
      "50",
      "60",
      "65",
      "55"
    ],
    "a": 3,
    "e": "AB=25；射影关系AC²=AB×AD=225、BC²=AB×DB=400，得两腰原长15、20。平行线过半高，截线为12.5，梯形另两边各剩一半，周长25+12.5+7.5+10=55。",
    "tr": "原三角形周长60不等于梯形周长；平行截取时各线性尺寸同比分割。",
    "signal": "先用高的分段恢复必要边长，再用相似处理截取，不必算斜率。",
    "family": "直角高分段与平行截取",
    "template": "直角高分段与平行截取",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:093",
    "replacesUid": "hand100:093",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "几何",
    "t": "综合建模",
    "s": "边长10厘米的实心正方体，从某面中央沿垂直该面的方向挖通一条正方形直孔，孔的四侧面分别平行于原正方体侧面。挖后剩余体积是原来的84%。剩余立体表面积多少平方厘米？",
    "o": [
      "728",
      "568",
      "600",
      "696"
    ],
    "a": 0,
    "e": "挖走体积160，孔长10，截面积16、边长4。原表面600减去两个孔口32，加四个孔壁4×4×10=160，得728。",
    "tr": "去掉物体体积却可能增加表面积；孔壁必须计入。",
    "signal": "体积损失锁截面，再逐类数消失的面与新暴露的面。",
    "family": "挖孔体积比反推新增表面",
    "template": "挖孔体积比反推新增表面",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:094",
    "replacesUid": "hand100:094",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "周期",
    "t": "综合建模",
    "s": "某人从星期一开始按工作3天、休息1天循环，统计连续30天。只有既是他的工作日、又是星期一至星期五的日子才办理业务。共有多少个办理业务日？",
    "o": [
      "15",
      "17",
      "16",
      "18"
    ],
    "a": 1,
    "e": "前28天为4和7的共同周期：20个周内日，其中4、8、12、16、24日为其休息日（20、28日是周末），故15个办理日；余29、30日为周一二且都工作，再加2得17。",
    "tr": "不能用30×3/4×5/7直接取整，休息与周末有固定重合位置。",
    "signal": "用共同周期算两个日历的交集，再补末尾不完整周期。",
    "family": "出勤周期与星期营业交集",
    "template": "出勤周期与星期营业交集",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:095",
    "replacesUid": "hand100:095",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "周期",
    "t": "综合建模",
    "s": "第1天为星期一，三项维护原计划分别从第1天起每4、7、9天一次。原定周六或周日的维护顺延至紧接的周一；后续原计划仍从第1天计算，不受顺延影响。三项维护下次实际同日进行，是第几天？",
    "o": [
      "22",
      "28",
      "29",
      "253"
    ],
    "a": 2,
    "e": "每7天那项固定周一，所以只查8、15、22、29日。前两项在15、22日可碰面，但第三项原定10、19日均不顺延；第三项第28日为周日，顺延29，与另外两项第29日同时，故29。",
    "tr": "直接取4、7、9的公倍数忽略顺延；顺延后不能重置后续周期。",
    "signal": "先用固定星期的一项稀疏筛日期，再查其余原计划落在当天或之前周末。",
    "family": "周末顺延与原始周期候选",
    "template": "周末顺延与原始周期候选",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:096",
    "replacesUid": "hand100:096",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "利润",
    "t": "综合建模",
    "s": "某商品成本30元，售价70元时日销100件；每降价3元，需求增20件。仅允许降价0至10次，次数为整数；所有需求必须满足，但每日最多供应160件。不计其他费用，最大日利润多少元？",
    "o": [
      "4800",
      "4900",
      "5040",
      "4960"
    ],
    "a": 3,
    "e": "降k次需求100+20k≤160，所以k≤3。利润(40−3k)(100+20k)，k=0、1、2、3对应4000、4440、4760、4960，取4960；无容量时k=4的5040不可行。",
    "tr": "不能把供货上限忽略，也不能擅自将超过160的需求截断出售，题目要求全部满足。",
    "signal": "先用容量删掉不可行的价格档，再优化可行的整数利润。",
    "family": "离散价量与销售容量",
    "template": "离散价量与销售容量",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:097",
    "replacesUid": "hand100:097",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "经济",
    "t": "综合建模",
    "s": "物资只能整包购买：小包7件100元，大包11件150元。需至少80件，且多余不能超过3件，包数为非负整数。最低采购费多少元？",
    "o": [
      "1100",
      "1050",
      "1150",
      "1200"
    ],
    "a": 0,
    "e": "总数只能80至83。固定大包b=0至7检验小包整数，可行(小,大)为(10,1)、(7,3)、(4,5)、(2,6)，费用1150、1150、1150、1100，取1100。",
    "tr": "大包单价低也不能直接买8大包：88件超过余量限制。",
    "signal": "上下界把总数压成短区间，再用整除筛整包组合。",
    "family": "整包采购与余量区间",
    "template": "整包采购与余量区间",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": true,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:098",
    "replacesUid": "hand100:098",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "容斥",
    "t": "二步钩",
    "s": "100人至少参加甲乙丙项目中的一项。各项目人数分别60、55、50，且恰好参加一项的有40人。三项都参加的有多少人？",
    "o": [
      "10",
      "5",
      "15",
      "25"
    ],
    "a": 1,
    "e": "设恰两项x、恰三项y，有x+y=60；总参与次数165，扣恰一项40，得2x+3y=125。减去2(x+y)=120，得y=5。",
    "tr": "三集合的总参与次数165不是并集人数，按参加次数分层更少未知量。",
    "signal": "不急着设三个两两交集，直接统计每个人被计了几次。",
    "family": "三集合按参加次数分层",
    "template": "三集合按参加次数分层",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：按参与次数分层后两条总量关系消元，不需逐一枚举三个两两交集。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:099",
    "replacesUid": "hand100:099",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "深化",
    "h": "数列",
    "t": "二步钩",
    "s": "某项目每月经费按等差数列增加，前3个月合计1800元，前6个月合计4500元。按同一规律持续，第7至12个月共多少元？",
    "o": [
      "7200",
      "7500",
      "8100",
      "9000"
    ],
    "a": 2,
    "e": "第4至6月合2700，比前3月多900；每项相隔3个月，故900=9d，月增100。前3月均600是第2月，首月500；第7月1100、第12月1600，后半年共6×1350=8100。",
    "tr": "前6个月总和不等于第4至6月总和，须先相减；增长比较还含3项权重。",
    "signal": "等长时间块相减消掉首项，再用等差平均求目标块。",
    "family": "前后半段总量消元",
    "template": "前后半段总量消元",
    "cost": "中",
    "targetSeconds": 75,
    "difficultyBasis": "隐藏状态、条件空间或事件切换；本题：等长季度块的差直接锁增长，再求后两季度总和，无需逐月列多变量。",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  },
  {
    "uid": "hand100:v2:100",
    "replacesUid": "hand100:100",
    "sourceType": "mock",
    "sourceLabel": "原创模拟·百题v2",
    "generator": "Codex逐题编写（非人工教师署名）",
    "level": "综合",
    "h": "组合概率",
    "t": "综合建模",
    "s": "8天内完成甲乙两门课程，甲需连续2整天，乙需连续3整天，同一天最多学一门，其余3天休息。等可能选择一种满足连续学习要求的日程，3个休息日两两不相邻的概率是多少？",
    "o": [
      "1/20",
      "1/5",
      "1/4",
      "1/10"
    ],
    "a": 3,
    "e": "把甲2天、乙3天各压成不同的块，与3个相同休息日共5对象，共5!/3!=20种。休息不邻必须分别占两课程块的前、中、后3个空隙，课程块次序2种，概率2/20=1/10。",
    "tr": "课程块虽长度不同，压缩日程与原日程仍一一对应；不能把休息日当3个不同对象。",
    "signal": "先验证压缩的一一对应，再用插空法数事件。",
    "family": "不同长度连续块与休息不邻",
    "template": "不同长度连续块与休息不邻",
    "cost": "高",
    "targetSeconds": 100,
    "difficultyBasis": "至少两个约束共用中间量，或需要上界与可行构造闭合",
    "optionValue": "未实测",
    "canEstimate": false,
    "canPlugOptions": false,
    "skipReason": "",
    "revision": "2.0"
  }
];
